//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDiagram")]

namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainClass JSRBBRProyectoIPSDiagram
	/// Description for UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDiagram.DisplayName", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDiagram.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("cb1c5cb4-3f05-4493-9e12-1b2f664a2914")]
	public partial class JSRBBRProyectoIPSDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.ClaseAbstracta)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClaseAbstracta newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClaseAbstracta(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.OperacionNormal)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaOperacionNormal newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaOperacionNormal(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.OperacionEnriquecida)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaOperacionEnriquecida newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaOperacionEnriquecida(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.ClaseEnriquecida)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClaseEnriquecida newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClaseEnriquecida(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClase)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.ClaseIncludesTargetClase)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.ClaseRelatesTargetClase)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.Clase)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClase newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClase(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.Atributo)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaAtributo newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaAtributo(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionHerencia newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionHerencia(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases)
			{
				global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelaciones newShape = new global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelaciones(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClase.DecoratorsInitialized += MetaforaClaseDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClaseAbstracta.DecoratorsInitialized += MetaforaClaseAbstractaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaAtributo.DecoratorsInitialized += MetaforaAtributoDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaOperacionNormal.DecoratorsInitialized += MetaforaOperacionNormalDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaOperacionEnriquecida.DecoratorsInitialized += MetaforaOperacionEnriquecidaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaClaseEnriquecida.DecoratorsInitialized += MetaforaClaseEnriquecidaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionHerencia.DecoratorsInitialized += MetaforaRelacionHerenciaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelaciones.DecoratorsInitialized += MetaforaRelacionesDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional.DecoratorsInitialized += MetaforaRelacionRelacionalDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva.DecoratorsInitialized += MetaforaRelacionInclusivaDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial.DecoratorsInitialized += MetaforaRelacionReferencialDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaClase.
		/// </summary>
		internal static partial class MetaforaClaseDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaClase.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.Clase.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreClaseDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaClaseAbstracta.
		/// </summary>
		internal static partial class MetaforaClaseAbstractaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaClaseAbstracta.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.Clase.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreClaseAbstractaDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaAtributo.
		/// </summary>
		internal static partial class MetaforaAtributoDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaAtributo.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.Atributo.nombreCalculadoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaOperacionNormal.
		/// </summary>
		internal static partial class MetaforaOperacionNormalDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaOperacionNormal.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.Operacion.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.Operacion.valorRetornoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "valorRetorno").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaOperacionEnriquecida.
		/// </summary>
		internal static partial class MetaforaOperacionEnriquecidaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaOperacionEnriquecida.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				MetaforaOperacionNormalDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.Operacion.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.Operacion.valorRetornoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "valorRetorno").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.OperacionEnriquecida.colorLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "colorLetraDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.OperacionEnriquecida.tipoLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "tipoLetraDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaClaseEnriquecida.
		/// </summary>
		internal static partial class MetaforaClaseEnriquecidaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaClaseEnriquecida.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.Clase.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRelacionHerencia.
		/// </summary>
		internal static partial class MetaforaRelacionHerenciaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRelacionHerencia.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija.disjuntaSolapadaCalculadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "disjuntaSolapadaDec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija.totalParcialCalculadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "totalParcialDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRelaciones.
		/// </summary>
		internal static partial class MetaforaRelacionesDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRelaciones.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad1DomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidad1Dec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad2DomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidad2Dec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRelacionRelacional.
		/// </summary>
		internal static partial class MetaforaRelacionRelacionalDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRelacionRelacional.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				MetaforaRelacionesDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad1DomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidad1Dec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad2DomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidad2Dec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRelacionInclusiva.
		/// </summary>
		internal static partial class MetaforaRelacionInclusivaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRelacionInclusiva.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				MetaforaRelacionesDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad1DomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidad1Dec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad2DomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidad2Dec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRelacionReferencial.
		/// </summary>
		internal static partial class MetaforaRelacionReferencialDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRelacionReferencial.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				MetaforaRelacionesDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad1DomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidad1Dec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad2DomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "cardinalidad2Dec").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "nombreDec").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.JSRBBRProyectoIPS.HerenciaConnectAction herenciaConnectAction;
		private global::UPM_IPS.JSRBBRProyectoIPS.RelacionAsociativaConnectAction relacionAsociativaConnectAction;
		private global::UPM_IPS.JSRBBRProyectoIPS.RelacionInclusivaConnectAction relacionInclusivaConnectAction;
		private global::UPM_IPS.JSRBBRProyectoIPS.RelacionReferencialConnectAction relacionReferencialConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSToolboxHelper.HerenciaFilterString))
				{
					if (this.herenciaConnectAction == null)
					{
						this.herenciaConnectAction = new global::UPM_IPS.JSRBBRProyectoIPS.HerenciaConnectAction(this);
						this.herenciaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.herenciaConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSToolboxHelper.RelacionAsociativaFilterString))
				{
					if (this.relacionAsociativaConnectAction == null)
					{
						this.relacionAsociativaConnectAction = new global::UPM_IPS.JSRBBRProyectoIPS.RelacionAsociativaConnectAction(this);
						this.relacionAsociativaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relacionAsociativaConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSToolboxHelper.RelacionInclusivaFilterString))
				{
					if (this.relacionInclusivaConnectAction == null)
					{
						this.relacionInclusivaConnectAction = new global::UPM_IPS.JSRBBRProyectoIPS.RelacionInclusivaConnectAction(this);
						this.relacionInclusivaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relacionInclusivaConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSToolboxHelper.RelacionReferencialFilterString))
				{
					if (this.relacionReferencialConnectAction == null)
					{
						this.relacionReferencialConnectAction = new global::UPM_IPS.JSRBBRProyectoIPS.RelacionReferencialConnectAction(this);
						this.relacionReferencialConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relacionReferencialConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.herenciaConnectAction != null)
					{
						this.herenciaConnectAction.Dispose();
						this.herenciaConnectAction = null;
					}
					if(this.relacionAsociativaConnectAction != null)
					{
						this.relacionAsociativaConnectAction.Dispose();
						this.relacionAsociativaConnectAction = null;
					}
					if(this.relacionInclusivaConnectAction != null)
					{
						this.relacionInclusivaConnectAction.Dispose();
						this.relacionInclusivaConnectAction = null;
					}
					if(this.relacionReferencialConnectAction != null)
					{
						this.relacionReferencialConnectAction.Dispose();
						this.relacionReferencialConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// JSRBBRProyectoIPSDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xcb1c5cb4, 0x3f05, 0x4493, 0x9e, 0x12, 0x1b, 0x2f, 0x66, 0x4a, 0x29, 0x14);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public JSRBBRProyectoIPSDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public JSRBBRProyectoIPSDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.JSRBBRProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseAbstracta), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.OperacionNormal), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.OperacionEnriquecida), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseEnriquecida), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseIncludesTargetClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseRelatesTargetClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.Clase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.Atributo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.JSRBBRProyectoIPS.ClaseAbstracta)
				{
					parentElement = GetParentForClaseAbstracta((global::UPM_IPS.JSRBBRProyectoIPS.ClaseAbstracta)childElement);
				} else
				if(childElement is global::UPM_IPS.JSRBBRProyectoIPS.OperacionNormal)
				{
					parentElement = GetParentForOperacionNormal((global::UPM_IPS.JSRBBRProyectoIPS.OperacionNormal)childElement);
				} else
				if(childElement is global::UPM_IPS.JSRBBRProyectoIPS.OperacionEnriquecida)
				{
					parentElement = GetParentForOperacionEnriquecida((global::UPM_IPS.JSRBBRProyectoIPS.OperacionEnriquecida)childElement);
				} else
				if(childElement is global::UPM_IPS.JSRBBRProyectoIPS.ClaseEnriquecida)
				{
					parentElement = GetParentForClaseEnriquecida((global::UPM_IPS.JSRBBRProyectoIPS.ClaseEnriquecida)childElement);
				} else
				if(childElement is global::UPM_IPS.JSRBBRProyectoIPS.Clase)
				{
					parentElement = GetParentForClase((global::UPM_IPS.JSRBBRProyectoIPS.Clase)childElement);
				} else
				if(childElement is global::UPM_IPS.JSRBBRProyectoIPS.Atributo)
				{
					parentElement = GetParentForAtributo((global::UPM_IPS.JSRBBRProyectoIPS.Atributo)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.JSRBBRProyectoIPS.TapizClases GetParentForClase( global::UPM_IPS.JSRBBRProyectoIPS.Clase root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JSRBBRProyectoIPS.TapizClases result = root.TapizClases;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JSRBBRProyectoIPS.TapizClases GetParentForClaseAbstracta( global::UPM_IPS.JSRBBRProyectoIPS.Clase root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JSRBBRProyectoIPS.TapizClases result = root.TapizClases;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JSRBBRProyectoIPS.TapizClases GetParentForAtributo( global::UPM_IPS.JSRBBRProyectoIPS.Atributo root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JSRBBRProyectoIPS.Clase root2 = root.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JSRBBRProyectoIPS.TapizClases result = root2.TapizClases;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JSRBBRProyectoIPS.TapizClases GetParentForOperacionNormal( global::UPM_IPS.JSRBBRProyectoIPS.OperacionNormal root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JSRBBRProyectoIPS.Clase root2 = root.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JSRBBRProyectoIPS.TapizClases result = root2.TapizClases;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JSRBBRProyectoIPS.TapizClases GetParentForOperacionEnriquecida( global::UPM_IPS.JSRBBRProyectoIPS.OperacionEnriquecida root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JSRBBRProyectoIPS.Clase root2 = root.ClaseEnriquecida as global::UPM_IPS.JSRBBRProyectoIPS.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::UPM_IPS.JSRBBRProyectoIPS.TapizClases result = root2.TapizClases;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.JSRBBRProyectoIPS.TapizClases GetParentForClaseEnriquecida( global::UPM_IPS.JSRBBRProyectoIPS.Clase root )
			{
				// Segments 0 and 1
				global::UPM_IPS.JSRBBRProyectoIPS.TapizClases result = root.TapizClases;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija.disjuntaSolapadaCalculadaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionHerencia.FindMetaforaRelacionHerenciaDecorator("disjuntaSolapadaDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija.totalParcialCalculadaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionHerencia.FindMetaforaRelacionHerenciaDecorator("totalParcialDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad1DomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelaciones.FindMetaforaRelacionesDecorator("cardinalidad1Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional.FindMetaforaRelacionRelacionalDecorator("cardinalidad1Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva.FindMetaforaRelacionInclusivaDecorator("cardinalidad1Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial.FindMetaforaRelacionReferencialDecorator("cardinalidad1Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional.FindMetaforaRelacionRelacionalDecorator("cardinalidad1Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClase.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva.FindMetaforaRelacionInclusivaDecorator("cardinalidad1Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseIncludesTargetClase.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial.FindMetaforaRelacionReferencialDecorator("cardinalidad1Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseRelatesTargetClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.cardinalidad2DomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelaciones.FindMetaforaRelacionesDecorator("cardinalidad2Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional.FindMetaforaRelacionRelacionalDecorator("cardinalidad2Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva.FindMetaforaRelacionInclusivaDecorator("cardinalidad2Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial.FindMetaforaRelacionReferencialDecorator("cardinalidad2Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional.FindMetaforaRelacionRelacionalDecorator("cardinalidad2Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClase.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva.FindMetaforaRelacionInclusivaDecorator("cardinalidad2Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseIncludesTargetClase.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial.FindMetaforaRelacionReferencialDecorator("cardinalidad2Dec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseRelatesTargetClase.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.nombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelaciones.FindMetaforaRelacionesDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional.FindMetaforaRelacionRelacionalDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva.FindMetaforaRelacionInclusivaDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial.FindMetaforaRelacionReferencialDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionRelacional.FindMetaforaRelacionRelacionalDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClase.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionInclusiva.FindMetaforaRelacionInclusivaDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseIncludesTargetClase.DomainClassId);
					}
					decorator = global::UPM_IPS.JSRBBRProyectoIPS.MetaforaRelacionReferencial.FindMetaforaRelacionReferencialDecorator("nombreDec");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.JSRBBRProyectoIPS.ClaseRelatesTargetClase.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseInheritsClaseHija), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClases), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseReferencesTargetClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseIncludesTargetClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ClaseRelatesTargetClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDiagram diagram = linkShape.Diagram as global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
