//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainModel JSRBBRProyectoIPSDomainModel
	/// Description for UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("8aeb048e-8ad0-4a10-bef5-8a335450f2b0")]
	public partial class JSRBBRProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// JSRBBRProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x8aeb048e, 0x8ad0, 0x4a10, 0xbe, 0xf5, 0x8a, 0x33, 0x54, 0x50, 0xf2, 0xb0);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public JSRBBRProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(TapizClases),
				typeof(Clase),
				typeof(Atributo),
				typeof(AtributoID),
				typeof(Parametro),
				typeof(OperacionNormal),
				typeof(ClaseAbstracta),
				typeof(OperacionAbstracta),
				typeof(ClaseEnriquecida),
				typeof(AtributoEnriquecido),
				typeof(OperacionEnriquecida),
				typeof(Operacion),
				typeof(AtributoPadre),
				typeof(TapizClasesHasClase),
				typeof(ClaseHasAtributo),
				typeof(ClaseHasOperacion),
				typeof(ClaseInheritsClaseHija),
				typeof(ClaseAbstractaHasOperacionAbstracta),
				typeof(ClaseReferencesTargetClase),
				typeof(ClaseIncludesTargetClase),
				typeof(ClaseRelatesTargetClase),
				typeof(ClaseReferencesTargetClases),
				typeof(ClaseEnriquecidaHasOperacionEnriquecida),
				typeof(OperacionHasParametros),
				typeof(ClaseEnriquecidaHasAtributoEnriquecido),
				typeof(ClaseHasAtributoID),
				typeof(JSRBBRProyectoIPSDiagram),
				typeof(MetaforaRelacionHerencia),
				typeof(MetaforaRelaciones),
				typeof(MetaforaRelacionRelacional),
				typeof(MetaforaRelacionInclusiva),
				typeof(MetaforaRelacionReferencial),
				typeof(MetaforaConectorAtributoID),
				typeof(MetaforaConectorOperacionNormal),
				typeof(MetaforaConectorOperacionAbstracta),
				typeof(MetaforaConectorOperacionEnriquecida),
				typeof(MetaforaAtributoID),
				typeof(MetaforaClase),
				typeof(MetaforaClaseAbstracta),
				typeof(MetaforaClaseEnriquecida),
				typeof(MetaforaOperacionNormal),
				typeof(MetaforaOperacionAbstracta),
				typeof(MetaforaOperacionEnriquecida),
				typeof(global::UPM_IPS.JSRBBRProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.JSRBBRProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.JSRBBRProyectoIPS.ConnectorRolePlayerChanged),
				typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemAddRule),
				typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemDeleteRule),
				typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemRolePlayerChangeRule),
				typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(TapizClases), "nombre", TapizClases.nombreDomainPropertyId, typeof(TapizClases.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "nombre", Clase.nombreDomainPropertyId, typeof(Clase.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "nombre", Parametro.nombreDomainPropertyId, typeof(Parametro.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "tipoDatos", Parametro.tipoDatosDomainPropertyId, typeof(Parametro.tipoDatosPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "entradaSalida", Parametro.entradaSalidaDomainPropertyId, typeof(Parametro.entradaSalidaPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "nombreCalculado", Parametro.nombreCalculadoDomainPropertyId, typeof(Parametro.nombreCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "colorFondo", ClaseEnriquecida.colorFondoDomainPropertyId, typeof(ClaseEnriquecida.colorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "colorLetraNombre", ClaseEnriquecida.colorLetraNombreDomainPropertyId, typeof(ClaseEnriquecida.colorLetraNombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "tipoLetraNombre", ClaseEnriquecida.tipoLetraNombreDomainPropertyId, typeof(ClaseEnriquecida.tipoLetraNombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "alineacion", ClaseEnriquecida.alineacionDomainPropertyId, typeof(ClaseEnriquecida.alineacionPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "tipoLetra", AtributoEnriquecido.tipoLetraDomainPropertyId, typeof(AtributoEnriquecido.tipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "colorLetra", AtributoEnriquecido.colorLetraDomainPropertyId, typeof(AtributoEnriquecido.colorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "booleano", AtributoEnriquecido.booleanoDomainPropertyId, typeof(AtributoEnriquecido.booleanoPropertyHandler)),
				new DomainMemberInfo(typeof(OperacionEnriquecida), "tipoLetra", OperacionEnriquecida.tipoLetraDomainPropertyId, typeof(OperacionEnriquecida.tipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(OperacionEnriquecida), "colorLetra", OperacionEnriquecida.colorLetraDomainPropertyId, typeof(OperacionEnriquecida.colorLetraPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "nombre", Operacion.nombreDomainPropertyId, typeof(Operacion.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "valorRetorno", Operacion.valorRetornoDomainPropertyId, typeof(Operacion.valorRetornoPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "operacionCalculada", Operacion.operacionCalculadaDomainPropertyId, typeof(Operacion.operacionCalculadaPropertyHandler)),
				new DomainMemberInfo(typeof(Operacion), "modificador", Operacion.modificadorDomainPropertyId, typeof(Operacion.modificadorPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoPadre), "nombre", AtributoPadre.nombreDomainPropertyId, typeof(AtributoPadre.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(AtributoPadre), "modificador", AtributoPadre.modificadorDomainPropertyId, typeof(AtributoPadre.modificadorPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoPadre), "nombreCalculado", AtributoPadre.nombreCalculadoDomainPropertyId, typeof(AtributoPadre.nombreCalculadoPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseInheritsClaseHija), "disjuntaSolapada", ClaseInheritsClaseHija.disjuntaSolapadaDomainPropertyId, typeof(ClaseInheritsClaseHija.disjuntaSolapadaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseInheritsClaseHija), "totalParcial", ClaseInheritsClaseHija.totalParcialDomainPropertyId, typeof(ClaseInheritsClaseHija.totalParcialPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesTargetClases), "nombre", ClaseReferencesTargetClases.nombreDomainPropertyId, typeof(ClaseReferencesTargetClases.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesTargetClases), "cardinalidad1", ClaseReferencesTargetClases.cardinalidad1DomainPropertyId, typeof(ClaseReferencesTargetClases.cardinalidad1PropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesTargetClases), "cardinalidad2", ClaseReferencesTargetClases.cardinalidad2DomainPropertyId, typeof(ClaseReferencesTargetClases.cardinalidad2PropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesTargetClases), "cardinalidad1Calculada", ClaseReferencesTargetClases.cardinalidad1CalculadaDomainPropertyId, typeof(ClaseReferencesTargetClases.cardinalidad1CalculadaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseReferencesTargetClases), "cardinalidad2Calculada", ClaseReferencesTargetClases.cardinalidad2CalculadaDomainPropertyId, typeof(ClaseReferencesTargetClases.cardinalidad2CalculadaPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizClasesHasClase), "TapizClases", TapizClasesHasClase.TapizClasesDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizClasesHasClase), "Clase", TapizClasesHasClase.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Clase", ClaseHasAtributo.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Atributo", ClaseHasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacion), "Clase", ClaseHasOperacion.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasOperacion), "OperacionNormal", ClaseHasOperacion.OperacionNormalDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseInheritsClaseHija), "SourceClase", ClaseInheritsClaseHija.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseInheritsClaseHija), "TargetClase", ClaseInheritsClaseHija.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseAbstractaHasOperacionAbstracta), "ClaseAbstracta", ClaseAbstractaHasOperacionAbstracta.ClaseAbstractaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseAbstractaHasOperacionAbstracta), "OperacionAbstracta", ClaseAbstractaHasOperacionAbstracta.OperacionAbstractaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesTargetClase), "SourceClase", ClaseReferencesTargetClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesTargetClase), "TargetClase", ClaseReferencesTargetClase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseIncludesTargetClase), "SourceClase", ClaseIncludesTargetClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseIncludesTargetClase), "TargetClase", ClaseIncludesTargetClase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseRelatesTargetClase), "SourceClase", ClaseRelatesTargetClase.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseRelatesTargetClase), "TargetClase", ClaseRelatesTargetClase.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesTargetClases), "SourceClase", ClaseReferencesTargetClases.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseReferencesTargetClases), "TargetClase", ClaseReferencesTargetClases.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasOperacionEnriquecida), "ClaseEnriquecida", ClaseEnriquecidaHasOperacionEnriquecida.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasOperacionEnriquecida), "OperacionEnriquecida", ClaseEnriquecidaHasOperacionEnriquecida.OperacionEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametros), "Operacion", OperacionHasParametros.OperacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(OperacionHasParametros), "Parametro", OperacionHasParametros.ParametroDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasAtributoEnriquecido), "ClaseEnriquecida", ClaseEnriquecidaHasAtributoEnriquecido.ClaseEnriquecidaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseEnriquecidaHasAtributoEnriquecido), "AtributoEnriquecido", ClaseEnriquecidaHasAtributoEnriquecido.AtributoEnriquecidoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributoID), "Clase", ClaseHasAtributoID.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributoID), "AtributoID", ClaseHasAtributoID.AtributoIDDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(30);
				createElementMap.Add(typeof(TapizClases), 0);
				createElementMap.Add(typeof(Clase), 1);
				createElementMap.Add(typeof(Atributo), 2);
				createElementMap.Add(typeof(AtributoID), 3);
				createElementMap.Add(typeof(Parametro), 4);
				createElementMap.Add(typeof(OperacionNormal), 5);
				createElementMap.Add(typeof(ClaseAbstracta), 6);
				createElementMap.Add(typeof(OperacionAbstracta), 7);
				createElementMap.Add(typeof(ClaseEnriquecida), 8);
				createElementMap.Add(typeof(AtributoEnriquecido), 9);
				createElementMap.Add(typeof(OperacionEnriquecida), 10);
				createElementMap.Add(typeof(JSRBBRProyectoIPSDiagram), 11);
				createElementMap.Add(typeof(MetaforaRelacionHerencia), 12);
				createElementMap.Add(typeof(MetaforaRelacionRelacional), 13);
				createElementMap.Add(typeof(MetaforaRelacionInclusiva), 14);
				createElementMap.Add(typeof(MetaforaRelacionReferencial), 15);
				createElementMap.Add(typeof(MetaforaConectorAtributoID), 16);
				createElementMap.Add(typeof(MetaforaConectorOperacionNormal), 17);
				createElementMap.Add(typeof(MetaforaConectorOperacionAbstracta), 18);
				createElementMap.Add(typeof(MetaforaConectorOperacionEnriquecida), 19);
				createElementMap.Add(typeof(MetaforaAtributoID), 20);
				createElementMap.Add(typeof(MetaforaClase), 21);
				createElementMap.Add(typeof(MetaforaClaseAbstracta), 22);
				createElementMap.Add(typeof(MetaforaClaseEnriquecida), 23);
				createElementMap.Add(typeof(MetaforaOperacionNormal), 24);
				createElementMap.Add(typeof(MetaforaOperacionAbstracta), 25);
				createElementMap.Add(typeof(MetaforaOperacionEnriquecida), 26);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new TapizClases(partition, propertyAssignments);
				case 1: return new Clase(partition, propertyAssignments);
				case 2: return new Atributo(partition, propertyAssignments);
				case 3: return new AtributoID(partition, propertyAssignments);
				case 4: return new Parametro(partition, propertyAssignments);
				case 5: return new OperacionNormal(partition, propertyAssignments);
				case 6: return new ClaseAbstracta(partition, propertyAssignments);
				case 7: return new OperacionAbstracta(partition, propertyAssignments);
				case 8: return new ClaseEnriquecida(partition, propertyAssignments);
				case 9: return new AtributoEnriquecido(partition, propertyAssignments);
				case 10: return new OperacionEnriquecida(partition, propertyAssignments);
				case 11: return new JSRBBRProyectoIPSDiagram(partition, propertyAssignments);
				case 12: return new MetaforaRelacionHerencia(partition, propertyAssignments);
				case 13: return new MetaforaRelacionRelacional(partition, propertyAssignments);
				case 14: return new MetaforaRelacionInclusiva(partition, propertyAssignments);
				case 15: return new MetaforaRelacionReferencial(partition, propertyAssignments);
				case 16: return new MetaforaConectorAtributoID(partition, propertyAssignments);
				case 17: return new MetaforaConectorOperacionNormal(partition, propertyAssignments);
				case 18: return new MetaforaConectorOperacionAbstracta(partition, propertyAssignments);
				case 19: return new MetaforaConectorOperacionEnriquecida(partition, propertyAssignments);
				case 20: return new MetaforaAtributoID(partition, propertyAssignments);
				case 21: return new MetaforaClase(partition, propertyAssignments);
				case 22: return new MetaforaClaseAbstracta(partition, propertyAssignments);
				case 23: return new MetaforaClaseEnriquecida(partition, propertyAssignments);
				case 24: return new MetaforaOperacionNormal(partition, propertyAssignments);
				case 25: return new MetaforaOperacionAbstracta(partition, propertyAssignments);
				case 26: return new MetaforaOperacionEnriquecida(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(13);
				createElementLinkMap.Add(typeof(TapizClasesHasClase), 0);
				createElementLinkMap.Add(typeof(ClaseHasAtributo), 1);
				createElementLinkMap.Add(typeof(ClaseHasOperacion), 2);
				createElementLinkMap.Add(typeof(ClaseInheritsClaseHija), 3);
				createElementLinkMap.Add(typeof(ClaseAbstractaHasOperacionAbstracta), 4);
				createElementLinkMap.Add(typeof(ClaseReferencesTargetClase), 5);
				createElementLinkMap.Add(typeof(ClaseIncludesTargetClase), 6);
				createElementLinkMap.Add(typeof(ClaseRelatesTargetClase), 7);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasOperacionEnriquecida), 8);
				createElementLinkMap.Add(typeof(OperacionHasParametros), 9);
				createElementLinkMap.Add(typeof(ClaseEnriquecidaHasAtributoEnriquecido), 10);
				createElementLinkMap.Add(typeof(ClaseHasAtributoID), 11);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizClasesHasClase(partition, roleAssignments, propertyAssignments);
				case 1: return new ClaseHasAtributo(partition, roleAssignments, propertyAssignments);
				case 2: return new ClaseHasOperacion(partition, roleAssignments, propertyAssignments);
				case 3: return new ClaseInheritsClaseHija(partition, roleAssignments, propertyAssignments);
				case 4: return new ClaseAbstractaHasOperacionAbstracta(partition, roleAssignments, propertyAssignments);
				case 5: return new ClaseReferencesTargetClase(partition, roleAssignments, propertyAssignments);
				case 6: return new ClaseIncludesTargetClase(partition, roleAssignments, propertyAssignments);
				case 7: return new ClaseRelatesTargetClase(partition, roleAssignments, propertyAssignments);
				case 8: return new ClaseEnriquecidaHasOperacionEnriquecida(partition, roleAssignments, propertyAssignments);
				case 9: return new OperacionHasParametros(partition, roleAssignments, propertyAssignments);
				case 10: return new ClaseEnriquecidaHasAtributoEnriquecido(partition, roleAssignments, propertyAssignments);
				case 11: return new ClaseHasAtributoID(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return JSRBBRProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (JSRBBRProyectoIPSDomainModel.resourceManager == null)
				{
					JSRBBRProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(JSRBBRProyectoIPSDomainModel).Assembly);
				}
				return JSRBBRProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return JSRBBRProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return JSRBBRProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (JSRBBRProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new JSRBBRProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					JSRBBRProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return JSRBBRProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (JSRBBRProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new JSRBBRProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					JSRBBRProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return JSRBBRProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::UPM_IPS.JSRBBRProyectoIPS.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JSRBBRProyectoIPSDeleteClosure : JSRBBRProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JSRBBRProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JSRBBRProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public JSRBBRProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.JSRBBRProyectoIPS.TapizClasesHasClase.ClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JSRBBRProyectoIPS.ClaseHasAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JSRBBRProyectoIPS.ClaseHasOperacion.OperacionNormalDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JSRBBRProyectoIPS.ClaseAbstractaHasOperacionAbstracta.OperacionAbstractaDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JSRBBRProyectoIPS.ClaseEnriquecidaHasOperacionEnriquecida.OperacionEnriquecidaDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JSRBBRProyectoIPS.OperacionHasParametros.ParametroDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JSRBBRProyectoIPS.ClaseEnriquecidaHasAtributoEnriquecido.AtributoEnriquecidoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.JSRBBRProyectoIPS.ClaseHasAtributoID.AtributoIDDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JSRBBRProyectoIPSCopyClosure : JSRBBRProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JSRBBRProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class JSRBBRProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public JSRBBRProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: entradaSalida
	/// Description for UPM_IPS.JSRBBRProyectoIPS.entradaSalida
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum entradaSalida
	{
		/// <summary>
		/// entrada
		/// Description for UPM_IPS.JSRBBRProyectoIPS.entradaSalida.entrada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.entradaSalida/entrada.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		entrada,
		/// <summary>
		/// salida
		/// Description for UPM_IPS.JSRBBRProyectoIPS.entradaSalida.salida
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.entradaSalida/salida.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		salida,
		/// <summary>
		/// entradaSalida
		/// Description for UPM_IPS.JSRBBRProyectoIPS.entradaSalida.entradaSalida
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.entradaSalida/entradaSalida.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		entradaSalida,
	}
}
namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: tipoDatos
	/// Description for UPM_IPS.JSRBBRProyectoIPS.tipoDatos
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum tipoDatos
	{
		/// <summary>
		/// Int
		/// Description for UPM_IPS.JSRBBRProyectoIPS.tipoDatos.Int
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.tipoDatos/Int.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		Int,
		/// <summary>
		/// String
		/// Description for UPM_IPS.JSRBBRProyectoIPS.tipoDatos.String
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.tipoDatos/String.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		String,
	}
}
namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: cardinalidades
	/// Description for UPM_IPS.JSRBBRProyectoIPS.cardinalidades
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum cardinalidades
	{
		/// <summary>
		/// c0
		/// Description for UPM_IPS.JSRBBRProyectoIPS.cardinalidades.c0
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.cardinalidades/c0.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		c0,
		/// <summary>
		/// c1
		/// Description for UPM_IPS.JSRBBRProyectoIPS.cardinalidades.c1
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.cardinalidades/c1.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		c1,
		/// <summary>
		/// c01
		/// Description for UPM_IPS.JSRBBRProyectoIPS.cardinalidades.c01
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.cardinalidades/c01.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		c01,
		/// <summary>
		/// c0N
		/// Description for UPM_IPS.JSRBBRProyectoIPS.cardinalidades.c0N
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.cardinalidades/c0N.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		c0N,
		/// <summary>
		/// c1N
		/// Description for UPM_IPS.JSRBBRProyectoIPS.cardinalidades.c1N
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.cardinalidades/c1N.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		c1N,
		/// <summary>
		/// MN
		/// Description for UPM_IPS.JSRBBRProyectoIPS.cardinalidades.MN
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.cardinalidades/MN.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		MN,
	}
}
namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: disjuntaSolapada
	/// Description for UPM_IPS.JSRBBRProyectoIPS.disjuntaSolapada
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum disjuntaSolapada
	{
		/// <summary>
		/// disjunta
		/// Description for UPM_IPS.JSRBBRProyectoIPS.disjuntaSolapada.disjunta
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.disjuntaSolapada/disjunta.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		disjunta,
		/// <summary>
		/// solapada
		/// Description for UPM_IPS.JSRBBRProyectoIPS.disjuntaSolapada.solapada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.disjuntaSolapada/solapada.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		solapada,
	}
}
namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: totalParcial
	/// Description for UPM_IPS.JSRBBRProyectoIPS.totalParcial
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum totalParcial
	{
		/// <summary>
		/// total
		/// Description for UPM_IPS.JSRBBRProyectoIPS.totalParcial.total
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.totalParcial/total.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		total,
		/// <summary>
		/// parcial
		/// Description for UPM_IPS.JSRBBRProyectoIPS.totalParcial.parcial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.totalParcial/parcial.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		parcial,
	}
}
namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: modificadorAtr
	/// Description for UPM_IPS.JSRBBRProyectoIPS.modificadorAtr
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum modificadorAtr
	{
		/// <summary>
		/// publico
		/// Description for UPM_IPS.JSRBBRProyectoIPS.modificadorAtr.publico
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.modificadorAtr/publico.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		publico = 2,
		/// <summary>
		/// privado
		/// Description for UPM_IPS.JSRBBRProyectoIPS.modificadorAtr.privado
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.modificadorAtr/privado.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		privado = 0,
		/// <summary>
		/// protegido
		/// Description for UPM_IPS.JSRBBRProyectoIPS.modificadorAtr.protegido
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.modificadorAtr/protegido.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		protegido = 1,
	}
}
namespace UPM_IPS.JSRBBRProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: atributoBool
	/// Description for UPM_IPS.JSRBBRProyectoIPS.atributoBool
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum atributoBool
	{
		/// <summary>
		/// text
		/// Description for UPM_IPS.JSRBBRProyectoIPS.atributoBool.text
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.atributoBool/text.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		text,
		/// <summary>
		/// radioButton
		/// Description for UPM_IPS.JSRBBRProyectoIPS.atributoBool.radioButton
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.atributoBool/radioButton.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		radioButton,
		/// <summary>
		/// checkbox
		/// Description for UPM_IPS.JSRBBRProyectoIPS.atributoBool.checkbox
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.JSRBBRProyectoIPS.atributoBool/checkbox.Description", typeof(global::UPM_IPS.JSRBBRProyectoIPS.JSRBBRProyectoIPSDomainModel), "UPM_IPS.JSRBBRProyectoIPS.GeneratedCode.DomainModelResx")]
		checkbox,
	}
}

