//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.JSRBBRProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "JSRBBR_DSLProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"JSRBBRProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID JSRBBRProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JSRBBRProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID JSRBBRProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JSRBBRProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewJSRBBRProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(JSRBBRProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string JSRBBRProyectoIPSPackageId = "f4711a2f-7d68-42cf-be73-4ae17ebbea56";
		
		// Editor factory identifier
		public const string JSRBBRProyectoIPSEditorFactoryId = "605b4e77-26aa-4613-8df5-bb269f415205";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string JSRBBRProyectoIPSModelExplorerToolWindowId = "cad70002-f3cb-4f65-aa7e-597f3155d8db";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.JSRBBRProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string JSRBBRProyectoIPSCommandSetId = "5276d78c-d68a-401a-8f4e-65cb231c7f1d";
	}
}